Console.WriteLine("Escreva um valor em metros:");
string entrada = Console.ReadLine()!;
double metro = Convert.ToDouble(entrada);
double kilometro = metro /1000;
double centimetro = metro * 100;
Console.Clear();
Console.ForegroundColor = ConsoleColor.Yellow;
Console.WriteLine($"{kilometro}Km");
Console.WriteLine($"{metro}m");
Console.WriteLine($"{centimetro}cm");
Console.ResetColor();
